/*
 * This Scala source file was auto generated by running 'gradle buildInit --type scala-library'
 * by 'manojma' at '6/16/17 12:45 PM' with Gradle 3.1
 *
 * @author manojma, @date 6/16/17 12:45 PM
 */
class Library {
  def someLibraryMethod(): Boolean = true
}
